### ISSUE TITLE
file not found unless url ends with forward slash

### ISSUE THREAD

**Issue by laymanmu** [hanami/hanami#480]
While following along in the [Getting Started Guide](http://hanamirb.org/guides/getting-started/) I am unable to open the url `/books` but `/books/` works fine.    

For example, after running this command:

`hanami generate action web books#index`

In the browser:

  /books
    - throws error in browser: `File not found: /books`

  /books/ 
    - opens a blank page with no errors.

auto generated routes file:

```  
  get '/books', to: 'books#index'
  # Configure your routes here
  # See: http://www.rubydoc.info/gems/hanami-router/#Usage
  get '/', to: 'home#index'
```
After continuing the guide and adding the file `apps/web/templates/books/index.html.erb`

Then the `spec/web/features/list_books_spec.rb` test still fails as before, `/books` still has the same error, and `/books/` shows the new html as expected with the 2 books.

Test:

```
Run options: --seed 41756

# Running:

...E

Finished in 0.020736s, 192.8970 runs/s, 192.8970 assertions/s.

  1) Error:
list books#test_0001_lists 2 books:
Capybara::ElementNotFound: Unable to find css "#books"
    /home/laymanmu/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/capybara-2.6.0/lib/capybara/node/finders.rb:43:in `block in find'
    /home/laymanmu/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/capybara-2.6.0/lib/capybara/node/base.rb:84:in `synchronize'
    /home/laymanmu/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/capybara-2.6.0/lib/capybara/node/finders.rb:32:in `find'
    /home/laymanmu/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/capybara-2.6.0/lib/capybara/session.rb:686:in `block (2 levels) in <class:Session>'
    /home/laymanmu/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/capybara-2.6.0/lib/capybara/session.rb:287:in `within'
    /home/laymanmu/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/capybara-2.6.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
    /home/laymanmu/www/bookshelf/spec/bookshelf/features/list_books_spec.rb:6:in `block (2 levels) in <top (required)>'

4 runs, 4 assertions, 0 failures, 1 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -I"lib:spec" -I"/home/laymanmu/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib" "/home/laymanmu/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "spec/**/*_spec.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by jodosha** [comment]
Possible new case reported in chat by @sylow

**Comment by jodosha** [comment]
@AlfonsoUceda This could be worth to investigate: https://github.com/joshbuddy/http_router/blob/907136f1111c076b5091db09ae0611330756b94c/lib/http_router.rb#L36-L42

**Comment by kristho91** [comment]
I was literally trying to pull out my hair because of this ;) Good to see it's already reported.

**Comment by jodosha** [comment]
Another case reported in chat by @sebabouche

**Comment by sebabouche** [comment]
Yep, I experienced the issue too. My only deviance from the tutorial was installing `minitest-reporters` in the `group :test` block.

**Comment by AlfonsoUceda** [comment]
@sebabouche @kristho91 and @laymanmu what SO do you use and terminal?

I was following the Starting Guide and I didn't have that problem with trailing slash :S could you post your info and Gemfile.lock?

**Comment by sebabouche** [comment]
I pushed my project to __[this repo](https://github.com/sebabouche/bookshelf)__

**Comment by sebabouche** [comment]
My config: 
+ ruby 2.2.3p173 
+ hanami v0.7.0

Is there anything else you might need?

**Comment by jodosha** [comment]
We found the problem and working on a patch.

**Comment by sebabouche** [comment]
:+1:

**Comment by tomajask** [comment]
I've also encountered an error in the spec: 
```ruby
# spec/web/features/add_book_spec.rb
require 'features_helper'

describe 'Books' do
  after do
    BookRepository.clear
  end

  it 'can create a new book' do
    visit '/books/new'

    within 'form#book-form' do
      fill_in 'Title',  with: 'New book'
      fill_in 'Author', with: 'Some author'

      click_button 'Create'
    end

    current_path.must_equal('//books/')
    assert page.has_content?('New book')
  end
end

```
To make it pass I needed to change the assertion to: `current_path.must_equal('//books/')`

I've put there a `binding.pry` and here is the result:
```ruby
    17:
 => 18:   binding.pry
    19:   current_path.must_equal('//books/')
    20:   assert page.has_content?('New book')
    21: end

[1] pry(#<Books>)> current_path
=> "//books/"
[2] pry(#<Books>)> current_url
=> "http://www.example.com//books/"
```

My `create` action looks like that:
```ruby
module Web::Controllers::Books
  class Create
    include Web::Action

    expose :book

    def call(params)
      @book = BookRepository.create(Book.new(params[:book]))

      redirect_to '/books/'
    end
  end
end
```
Without adding a slash to `redirect_to` I'm getting: `"File not found: /books\n"`

Here is my [repo](https://github.com/tomajask/hanami-framework)

**Comment by davydovanton** [comment]
@tomajask hello, I fixed this bug in this patch https://github.com/hanami/router/pull/89

**Comment by Freika** [comment]
Not fixed yet? I was going through "Getting Started" and encountered the problem exactly where @laymanmu did (Hanami Generators section).

**Comment by davydovanton** [comment]
@freika nope. I'm working on this now.

**Comment by davydovanton** [comment]
@sebabouche hello, sorry but I can't reproduce bug in your repository. Also I have @Freika repository with similar bug (https://github.com/Freika/hanami-bookshelf) but in this repository I cant' reproduce bug too.
Do you have any ideas how I can reproduce this? Thanks.

**Comment by sylow** [comment]
@davydovanton 
Here is my repository https://github.com/sylow/bookshelf

Run the tests and watch the test fail

`
require 'features_helper'

describe 'List books' do
  it 'displays each book on the page' do
    visit '/books'

    within '#books' do
      assert page.has_css?('.book', count: 2), "Expected to find 2 books"
    end
  end
end
`

**Comment by joneslee85** [comment]
@laymanmu @Freika @sylow can you please all verify if the patch by @davydovanton nail the bug? TIA

**Comment by davydovanton** [comment]
hey, @laymanmu @Freika @sylow.

You need to add this link to your gemfile and run tests or open `/books` page:
```
gem ‘hanami’, github: ‘davydovanton/lotus’, branch: 'fix-public-path-request’
```

**Comment by Freika** [comment]
@joneslee85 @davydovanton yep, bug fixed. Thanks!

**Comment by sylow** [comment]
@davydovanton 
'list_books_spec.rb' is working

But my root path is not finding the file this time, check this 'visit_home_spec.rb' test case please.

**Comment by jodosha** [comment]
Folks, can you please verify if https://github.com/hanami/hanami/pull/493 fixes the issue for you. Thanks all! :+1:

**Comment by jodosha** [comment]
@nghitran Reported this problem in chat again.

Steps to reproduce:

```shell
➜ hanami version
v0.7.1
➜ hanami new administration # THIS IS IMPORTANT, NAME **EXACTLY** IT "administration"
➜ cd administration && bundle update
➜ bundle exec hanami generate app admin
➜ bundle exec hanami generate action admin home#index --url=/
➜ bundle exec hanami server
```

Then visit `/admin` **TWICE**. The first time it's ok, the second time it's a `404`.

**Comment by davydovanton** [comment]
@jodosha yes, I can reproduce this bug. Also I know how we can solve this problem. We need to check file on `File.file?` too.

**Comment by jodosha** [comment]
@davydovanton Yup. Mr @AlfonsoUceda is already on it. Thank you :+1:

**Comment by davydovanton** [comment]
@jodosha I think we have a solution in https://github.com/hanami/hanami/pull/486. May be is better to merge this?

**Comment by jodosha** [comment]
@davydovanton Thanks for letting me notice about this. But that PR is implemented via a redundant check `index` and `end_with?`.

**Comment by davydovanton** [comment]
@jodosha yes. I think we need to remove unnecessary `index` from this PR and add test cases for current bug.

**Comment by jodosha** [comment]
@davydovanton ..and add tests ;)

**Comment by davydovanton** [comment]
yep, sorry :D

**Comment by jodosha** [comment]
@davydovanton Again, @AlfonsoUceda is working on it as we write. Don't worry, we're in good hands. :wink:

**Comment by jodosha** [comment]
Fixed by #506
