### ISSUE TITLE
--help options does not work correctly for some subcommands

### ISSUE THREAD

**Issue by igneus** [hanami/hanami#623]
`hanami new --help`, instead of describing available options, prints

```
ERROR: "hanami new" was called with no arguments
Usage: "hanami new APPLICATION_NAME"
```

This discovery made me try the `--help` option for all other subcommands (at least those listed by `hanami help`). This way I found a bug
- `hanami db --help`
- `hanami destroy --help`
- `hanami generate --help`

All these commands print

```
Usage:
  hanami help [COMMAND]

Describe subcommands or one specific subcommand
```

which is help for `hanami help`, not for the respective subcommands.

**(ADDED LATER)**

Help for sub-subcommands prints misleading usage synopsis: e.g. `hanami db create --help` prints

```
Usage:
  hanami create
```

instead of expected

```
Usage:
  hanami db create
```

**Comment by jodosha** [comment]
Fixed by #624

**Comment by igneus** [comment]
@jodosha It isn't really fixed as a whole. #624 only fixed `hanami new --help`, not the other similar issues mentioned above.

(I looked into these as well, but I wasn't able to solve them in a reasonable amount of time, so I submitted at least the fix for `hanami new --help`, which was easy enough to produce.)

**Comment by jodosha** [comment]
@igneus Sorry, you're right. Do you think you will have the time to work on this? Thank you very much!

**Comment by igneus** [comment]
I hope so, but I don't know when exactly. Anyone knowing how to fix it or willing to dig into it is most welcome to take it over.

**Comment by akhramov** [comment]
Regarding
> Help for sub-subcommands prints misleading usage synopsis

Other Thor-based projects experience the same issue as well.
calabash/run_loop#226

As a workaround we could override [Thor.banner](https://github.com/erikhuda/thor/blob/v0.19.1/lib/thor.rb#L367-L369) method:

```ruby
module Hanami
  module CliBase
    def banner(command, *)
      if namespace == 'hanami:cli'
        super
      else
        super(command, namespace, true)
      end
    end
  # ...
  end
end
```

It should fix the Usage banner:
```fish
% bundle exec bin/hanami db create --help

Usage:
  hanami db create
  ...

% bundle exec  bin/hanami new  --help
Usage:
  hanami new APPLICATION_NAME
  ...
```

**Comment by beauby** [comment]
Possibly related: `$ hanami help generate model` gives the same message as `$ hanami help generate`.

**Comment by jodosha** [comment]
My experience with Thor (the library that we use for CLI) is that isn't good enough for subcommands.

The current implementation of our commands `lib/hanami/commands` is messy. I'm planning a rewrite after 1.0.

**Comment by AlfonsoUceda** [comment]
@jodosha I think we should get rid of Thor and use OptionParser from Ruby standard library ;)

**Comment by charlie-wasp** [comment]
Is help still wanted? I'd like to give it a try

**Comment by jodosha** [comment]
@charlie-wasp Thanks for offering your help 😄 . If you can find a quick fix with `thor`, we can add merge it.

Otherwise, if it's too complicated, don't worry. We're thinking to get rid of `thor` and we can wait for this minor issue.

**Comment by docStonehenge** [comment]
Hello, guys ! I saw this problem on Hanami cli help descriptions, so I went further to check what could probably be. I've also found this old StackOverflow post, [http://stackoverflow.com/questions/5663519/namespacing-thor-commands-in-a-standalone-ruby-executable](url) which seems to be a similar problem with subcommands. As described above, overwriting Thor.banner solves this issue. Can I offer my assistance ?

**Comment by jodosha** [comment]
@docStonehenge Hi and thanks, please check with @charlie-wasp. @charlie-wasp Are you already working on this?

Please also read this: https://github.com/hanami/hanami/issues/623#issuecomment-276369218

**Comment by charlie-wasp** [comment]
@jodosha nope, didn't start yet, so @docStonehenge is very welcome to take over :smiley:

**Comment by docStonehenge** [comment]
@charlie-wasp thank you !! @jodosha, I am tackling on this and will open a PR asap. Thanks !

**Comment by docStonehenge** [comment]
@jodosha while working on this issue, I've noticed some other issues as well, for instance:

```
hanami generate model

ERROR: "hanami model" was called with no arguments
Usage: "hanami model NAME"
```

Fixing the banner for usage on help messages, the above becomes:

```
hanami generate model

ERROR: "hanami model" was called with no arguments
Usage: "hanami generate model NAME"
```

So, should I tackle on finding a fix for the "ERROR" message as well?

**Comment by mereghost** [comment]
@docStonehenge I'd say go for it. :D

**Comment by docStonehenge** [comment]
@jodosha I've been looking through Thor's source to figure out where those "ERROR/Usage" are been wrongly generated. Seems like a fix for that, and also for the banner on all usage synopsis was merged in the end of November/16, but not released yet. My suggestion for a fix would be similar to what's been done on Thor, overwriting the method to handle argument errors. 

Do you think it's best to wait for the next release and check for these fixes ?
