### ISSUE TITLE
Generating files over existing file behaves poorly

### ISSUE THREAD

**Issue by AlfonsoUceda** [hanami/hanami#855]
@cllns reported in hanami/cli repository this behaviour but the issue should be opened here. Please check issue https://github.com/hanami/cli/issues/22 for more info.

That wrong behaviour happens in all generators, we should make a deep analysis in CLI to avoid these weird problems.

**Comment by cllns** [comment]
This should fix the odd behavior to make `write` append instead of replace the beginning: https://github.com/hanami/utils/pull/239

For our purposes, we should probably change `write` to `rewrite` (and/or add a prompt asking the user what we should do).

**Comment by AlfonsoUceda** [comment]
@cllns have you tried the fix? It seems good but I think it doesn't fix it, try creating a branch

**Comment by AlfonsoUceda** [comment]
I created a branch with WIP to check how to fix this "problem". https://github.com/hanami/hanami/tree/fix-cli-generators

**Comment by jodosha** [comment]
@AlfonsoUceda May I ask you to decouple the fix from the enhancement?

The fix: CLI generators must always generate valid Ruby code, even if than used more than once. This is a must have.

The enhancement: Ask the user. We can discuss how to do.

**Comment by AlfonsoUceda** [comment]
@jodosha makes sense 👍

**Comment by jodosha** [comment]
Fixed by https://github.com/hanami/utils/pull/239
