### ISSUE TITLE
Cannot Create Hanami Project

### ISSUE THREAD

**Issue by bewitchingme** [hanami/hanami#987]
Ran into an issue creating a new app with Hanami; installed gem, did `hanami new blog` and it blew up like this:

```
Traceback (most recent call last):
        38: from /home/user/.gem/ruby/2.5.1/bin/hanami:23:in `<main>'
        37: from /home/user/.gem/ruby/2.5.1/bin/hanami:23:in `load'
        36: from /home/user/.gem/ruby/2.5.1/gems/hanami-1.3.1/bin/hanami:3:in `<top (required)>'
        35: from /home/user/.rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        34: from /home/user/.rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        33: from /home/user/.gem/ruby/2.5.1/gems/hanami-1.3.1/lib/hanami/cli/commands.rb:4:in `<top (required)>'
        32: from /home/user/.gem/ruby/2.5.1/gems/hanami-1.3.1/lib/hanami/cli/commands.rb:8:in `<module:Hanami>'
        31: from /home/user/.gem/ruby/2.5.1/gems/hanami-1.3.1/lib/hanami/cli/commands.rb:56:in `<class:CLI>'
        30: from /home/user/.gem/ruby/2.5.1/gems/hanami-1.3.1/lib/hanami/cli/commands.rb:89:in `<module:Commands>'
        29: from /home/user/.rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        28: from /home/user/.rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        27: from /home/user/.gem/ruby/2.5.1/gems/hanami-1.3.1/lib/hanami/cli/commands/command.rb:1:in `<top (required)>'
        26: from /home/user/.rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        25: from /home/user/.rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        24: from /home/user/.gem/ruby/2.5.1/gems/hanami-1.3.1/lib/hanami.rb:8:in `<top (required)>'
        23: from /home/user/.gem/ruby/2.5.1/gems/hanami-1.3.1/lib/hanami.rb:10:in `<module:Hanami>'
        22: from /home/user/.rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        21: from /home/user/.rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        20: from /home/user/.gem/ruby/2.5.1/gems/hanami-1.3.1/lib/hanami/frameworks.rb:2:in `<top (required)>'
        19: from /home/user/.rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        18: from /home/user/.rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        17: from /home/user/.gem/ruby/2.5.1/gems/hanami-validations-1.3.1/lib/hanami/validations.rb:1:in `<top (required)>'
        16: from /home/user/.rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        15: from /home/user/.rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        14: from /home/user/.gem/ruby/2.5.1/gems/dry-validation-0.11.1/lib/dry-validation.rb:1:in `<top (required)>'
        13: from /home/user/.rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        12: from /home/user/.rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        11: from /home/user/.gem/ruby/2.5.1/gems/dry-validation-0.11.1/lib/dry/validation.rb:39:in `<top (required)>'
        10: from /home/user/.rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         9: from /home/user/.rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         8: from /home/user/.gem/ruby/2.5.1/gems/dry-validation-0.11.1/lib/dry/validation/schema.rb:15:in `<top (required)>'
         7: from /home/user/.rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         6: from /home/user/.rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         5: from /home/user/.gem/ruby/2.5.1/gems/dry-validation-0.11.1/lib/dry/validation/schema/class_interface.rb:5:in `<top (required)>'
         4: from /home/user/.gem/ruby/2.5.1/gems/dry-validation-0.11.1/lib/dry/validation/schema/class_interface.rb:6:in `<module:Dry>'
         3: from /home/user/.gem/ruby/2.5.1/gems/dry-validation-0.11.1/lib/dry/validation/schema/class_interface.rb:7:in `<module:Validation>'
         2: from /home/user/.gem/ruby/2.5.1/gems/dry-validation-0.11.1/lib/dry/validation/schema/class_interface.rb:14:in `<class:Schema>'
         1: from /home/user/.gem/ruby/2.5.1/gems/dry-configurable-0.7.0/lib/dry/configurable.rb:110:in `setting'
/home/user/.gem/ruby/2.5.1/gems/dry-logic-0.5.0/lib/dry/logic/predicates.rb:17:in `nil?': wrong number of arguments (given 0, expected 1) (ArgumentError)
```

Help?

**Comment by 0xk175un3** [comment]
Probably it happened bc [dry-logic](https://github.com/dry-rb/dry-logic) was updated like 7 hours ago.  Inside [hanami-validations](https://github.com/hanami/validations) is dependency to [dry-validation](https://github.com/dry-rb/dry-validation). And `dry-validation` has dependency to error-maker `dry-logic`, not by version, but by master branch. Here it is [-->url<--](https://github.com/dry-rb/dry-validation/blob/a51c5936f682fe7c60bfdfec417334d71ba133a1/Gemfile#L7). So this cause error.

**Comment by flash-gordon** [comment]
https://rubygems.org/gems/dry-validation/versions/0.11.2 is out and should solve this issue. Please confirm.

**Comment by 0xk175un3** [comment]
@flash-gordon after `bundle update` it start works.

**Comment by jodosha** [comment]
@flash-gordon Thanks for taking care of this ❤️

**Comment by jodosha** [comment]
I released `hanami-validations` `1.3.2` to fix this problem.

**Comment by nessur** [comment]
can you update `Hanami-model` also?
```
Resolving dependencies...
Bundler could not find compatible versions for gem "dry-types":
  In Gemfile:
    hanami-validations (= 1.3.2) was resolved to 1.3.2, which depends on
      dry-validation (< 0.12, ~> 0.11.2) was resolved to 0.11.2, which depends on
        dry-types (~> 0.12.0)

    hanami-model (~> 1.3) was resolved to 1.3.1, which depends on
      dry-types (~> 0.11.0)
```

**Comment by nessur** [comment]
So, even using Hanami & Hanami-model 1.3.1, things are still broken.
```
$ hanami console
/Users/rguggemos/.rvm/gems/ruby-2.4.4/gems/dry-logic-0.5.0/lib/dry/logic/predicates.rb:17:in `nil?': wrong number of arguments (given 0, expected 1) (ArgumentError)
	from /Users/rguggemos/.rvm/gems/ruby-2.4.4/gems/dry-configurable-0.7.0/lib/dry/configurable.rb:110:in `setting'
	from /Users/rguggemos/.rvm/gems/ruby-2.4.4/gems/dry-validation-0.11.0/lib/dry/validation/schema/class_interface.rb:14:in `<class:Schema>'
```
BUT. I _can_ pin `dry-logic` to `0.4.2` and the app is able to boot once more.
